let
    Source = Excel.Workbook(File.Contents("D:\power_bi_projects\permit_pegah2.xlsx"), null, true),
    Sheet3_Sheet = Source{[Item="Sheet2",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet3_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"وضعیت درخواست", Int64.Type},{"dateRequest", type text},{"partRequest", type text}, {"كد تجهيز", type text}, {"EmergencyRequest", type text}, {"taskRequest", type text}, {"RequesterType", type text}, {"قسمت بهره‌بردار تجهيز", type text}, {"شيفت", type text}, {"maintenanceType", type text}, {"executerType", type text}, {"مجريان تعميرات", type text}, {"شرح عيب", type text}, {"کد تعمیرات پیشگیرانه", type text}, {"ارزش تخصصی پرمیت", type text}, {"سطح", type text}, {"نام درخواست کننده", type text}}),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "dateRequest", Splitter.SplitTextByDelimiter("/", QuoteStyle.None), {"dateRequest.1", "dateRequest.2", "dateRequest.3"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"dateRequest.1", type text}, {"dateRequest.2", Int64.Type}, {"dateRequest.3", Int64.Type}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"dateRequest.1", "year"}, {"dateRequest.2", "month"}}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns",{{"month", type text}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type2",{{"dateRequest.3", "day"}}),
    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1","12","اسفند",Replacer.ReplaceText,{"month"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","11","بهمن",Replacer.ReplaceText,{"month"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","10","دی",Replacer.ReplaceText,{"month"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","09","آذر",Replacer.ReplaceText,{"month"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","1","فروردین",Replacer.ReplaceText,{"month"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","2","اردیبهشت",Replacer.ReplaceText,{"month"}),
    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","3","خرداد",Replacer.ReplaceText,{"month"}),
    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","4","تیر",Replacer.ReplaceText,{"month"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","5","مرداد",Replacer.ReplaceText,{"month"}),
    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","6","شهریور",Replacer.ReplaceText,{"month"}),
    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","7","مهر",Replacer.ReplaceText,{"month"}),
    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","8","آبان",Replacer.ReplaceText,{"month"}),
    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","9","آذر",Replacer.ReplaceText,{"month"}),
    #"Changed Type3" = Table.TransformColumnTypes(#"Replaced Value12",{{"وضعیت درخواست", type text}}),
    #"Replaced Value13" = Table.ReplaceValue(#"Changed Type3","3","بسته",Replacer.ReplaceText,{"وضعیت درخواست"}),
    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","1","باز",Replacer.ReplaceText,{"وضعیت درخواست"}),
    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","2","نیاز به توقف",Replacer.ReplaceText,{"وضعیت درخواست"}),
    #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","نیاز به توقف","متوقف",Replacer.ReplaceText,{"وضعیت درخواست"})
in
    #"Replaced Value16"